CREATE TABLE `wp_term_relationships` (  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `term_order` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`object_id`,`term_taxonomy_id`),  KEY `term_taxonomy_id` (`term_taxonomy_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_term_relationships` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_term_relationships` VALUES('1', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('95', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('156', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('158', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('160', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('161', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('164', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('167', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('168', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('169', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('170', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('171', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('407', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('488', '2', '0');
INSERT INTO `wp_term_relationships` VALUES('489', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('490', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('491', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('492', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('493', '3', '0');
/*!40000 ALTER TABLE `wp_term_relationships` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
