CREATE TABLE `wp_usermeta` (  `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,  `meta_value` longtext COLLATE utf8mb4_unicode_520_ci,  PRIMARY KEY (`umeta_id`),  KEY `user_id` (`user_id`),  KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB AUTO_INCREMENT=78 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_usermeta` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_usermeta` VALUES('1', '1', 'nickname', 'admin');
INSERT INTO `wp_usermeta` VALUES('2', '1', 'first_name', '');
INSERT INTO `wp_usermeta` VALUES('3', '1', 'last_name', '');
INSERT INTO `wp_usermeta` VALUES('4', '1', 'description', '');
INSERT INTO `wp_usermeta` VALUES('5', '1', 'rich_editing', 'true');
INSERT INTO `wp_usermeta` VALUES('6', '1', 'syntax_highlighting', 'true');
INSERT INTO `wp_usermeta` VALUES('7', '1', 'comment_shortcuts', 'false');
INSERT INTO `wp_usermeta` VALUES('8', '1', 'admin_color', 'fresh');
INSERT INTO `wp_usermeta` VALUES('9', '1', 'use_ssl', '0');
INSERT INTO `wp_usermeta` VALUES('10', '1', 'show_admin_bar_front', 'true');
INSERT INTO `wp_usermeta` VALUES('11', '1', 'locale', '');
INSERT INTO `wp_usermeta` VALUES('12', '1', 'wp_capabilities', 'a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `wp_usermeta` VALUES('13', '1', 'wp_user_level', '10');
INSERT INTO `wp_usermeta` VALUES('14', '1', 'dismissed_wp_pointers', 'wp496_privacy,theme_editor_notice');
INSERT INTO `wp_usermeta` VALUES('15', '1', 'show_welcome_panel', '1');
INSERT INTO `wp_usermeta` VALUES('17', '1', 'wp_dashboard_quick_press_last_post_id', '607');
INSERT INTO `wp_usermeta` VALUES('18', '1', 'wp_user-settings', 'libraryContent=browse&editor=html');
INSERT INTO `wp_usermeta` VALUES('19', '1', 'wp_user-settings-time', '1563090646');
INSERT INTO `wp_usermeta` VALUES('20', '1', 'nav_menu_recently_edited', '2');
INSERT INTO `wp_usermeta` VALUES('21', '1', 'managenav-menuscolumnshidden', 'a:5:{i:0;s:11:\"link-target\";i:1;s:11:\"css-classes\";i:2;s:3:\"xfn\";i:3;s:11:\"description\";i:4;s:15:\"title-attribute\";}');
INSERT INTO `wp_usermeta` VALUES('22', '1', 'metaboxhidden_nav-menus', 'a:2:{i:0;s:12:\"add-post_tag\";i:1;s:15:\"add-post_format\";}');
INSERT INTO `wp_usermeta` VALUES('24', '1', 'session_tokens', 'a:1:{s:64:\"588fde2b8ac0de3831f02f7e31f233244d99096d09b5bbd2bdf2df2cf26045d5\";a:4:{s:10:\"expiration\";i:1573630728;s:2:\"ip\";s:3:\"::1\";s:2:\"ua\";s:117:\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15\";s:5:\"login\";i:1573457928;}}');
INSERT INTO `wp_usermeta` VALUES('25', '1', 'closedpostboxes_attributes', 'a:0:{}');
INSERT INTO `wp_usermeta` VALUES('26', '1', 'metaboxhidden_attributes', 'a:0:{}');
INSERT INTO `wp_usermeta` VALUES('27', '1', 'community-events-location', 'a:1:{s:2:\"ip\";s:11:\"91.73.128.0\";}');
INSERT INTO `wp_usermeta` VALUES('28', '2', 'nickname', 'hogtronix');
INSERT INTO `wp_usermeta` VALUES('29', '2', 'first_name', 'Russ');
INSERT INTO `wp_usermeta` VALUES('30', '2', 'last_name', 'Hogg');
INSERT INTO `wp_usermeta` VALUES('31', '2', 'description', '');
INSERT INTO `wp_usermeta` VALUES('32', '2', 'rich_editing', 'true');
INSERT INTO `wp_usermeta` VALUES('33', '2', 'syntax_highlighting', 'true');
INSERT INTO `wp_usermeta` VALUES('34', '2', 'comment_shortcuts', 'false');
INSERT INTO `wp_usermeta` VALUES('35', '2', 'admin_color', 'fresh');
INSERT INTO `wp_usermeta` VALUES('36', '2', 'use_ssl', '0');
INSERT INTO `wp_usermeta` VALUES('37', '2', 'show_admin_bar_front', 'true');
INSERT INTO `wp_usermeta` VALUES('38', '2', 'locale', '');
INSERT INTO `wp_usermeta` VALUES('39', '2', 'wp_capabilities', 'a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `wp_usermeta` VALUES('40', '2', 'wp_user_level', '10');
INSERT INTO `wp_usermeta` VALUES('41', '2', 'dismissed_wp_pointers', 'theme_editor_notice');
INSERT INTO `wp_usermeta` VALUES('42', '2', 'session_tokens', 'a:2:{s:64:\"3dd4485d9ddeca6fbde9fa065e9d48a2fdb1a5fbefe997b59e93c712137c33f4\";a:4:{s:10:\"expiration\";i:1570697653;s:2:\"ip\";s:14:\"217.217.154.40\";s:2:\"ua\";s:114:\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\";s:5:\"login\";i:1569488053;}s:64:\"fb79718cf9252d4525e193dba70ce353fbd9525412549482ad4998b5c47bde16\";a:4:{s:10:\"expiration\";i:1569669978;s:2:\"ip\";s:14:\"150.143.51.186\";s:2:\"ua\";s:114:\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\";s:5:\"login\";i:1569497178;}}');
INSERT INTO `wp_usermeta` VALUES('43', '2', 'wp_dashboard_quick_press_last_post_id', '583');
INSERT INTO `wp_usermeta` VALUES('44', '2', 'community-events-location', 'a:1:{s:2:\"ip\";s:13:\"217.217.154.0\";}');
INSERT INTO `wp_usermeta` VALUES('45', '2', 'nav_menu_recently_edited', '2');
INSERT INTO `wp_usermeta` VALUES('46', '2', 'managenav-menuscolumnshidden', 'a:5:{i:0;s:11:\"link-target\";i:1;s:11:\"css-classes\";i:2;s:3:\"xfn\";i:3;s:11:\"description\";i:4;s:15:\"title-attribute\";}');
INSERT INTO `wp_usermeta` VALUES('47', '2', 'metaboxhidden_nav-menus', 'a:5:{i:0;s:19:\"add-post-type-cover\";i:1;s:22:\"add-post-type-coverusp\";i:2;s:24:\"add-post-type-attributes\";i:3;s:12:\"add-post_tag\";i:4;s:15:\"add-post_format\";}');
INSERT INTO `wp_usermeta` VALUES('48', '2', 'closedpostboxes_dashboard', 'a:3:{i:0;s:18:\"dashboard_activity\";i:1;s:21:\"dashboard_quick_press\";i:2;s:17:\"dashboard_primary\";}');
INSERT INTO `wp_usermeta` VALUES('49', '2', 'metaboxhidden_dashboard', 'a:0:{}');
INSERT INTO `wp_usermeta` VALUES('50', '2', 'wp_yoast_notifications', 'a:1:{i:0;a:2:{s:7:\"message\";s:232:\"<strong>Huge SEO Issue: You\'re blocking access to robots.</strong> You must <a href=\"http://localhost:8888/eurorescue-wp/wp-admin/options-reading.php\">go to your Reading Settings</a> and uncheck the box for Search Engine Visibility.\";s:7:\"options\";a:9:{s:4:\"type\";s:5:\"error\";s:2:\"id\";s:32:\"wpseo-dismiss-blog-public-notice\";s:5:\"nonce\";N;s:8:\"priority\";i:1;s:9:\"data_json\";a:0:{}s:13:\"dismissal_key\";N;s:12:\"capabilities\";s:20:\"wpseo_manage_options\";s:16:\"capability_check\";s:3:\"all\";s:14:\"yoast_branding\";b:0;}}}');
INSERT INTO `wp_usermeta` VALUES('51', '1', 'wp_yoast_notifications', 'a:1:{i:0;a:2:{s:7:\"message\";s:232:\"<strong>Huge SEO Issue: You\'re blocking access to robots.</strong> You must <a href=\"http://localhost:8888/eurorescue-wp/wp-admin/options-reading.php\">go to your Reading Settings</a> and uncheck the box for Search Engine Visibility.\";s:7:\"options\";a:9:{s:4:\"type\";s:5:\"error\";s:2:\"id\";s:32:\"wpseo-dismiss-blog-public-notice\";s:5:\"nonce\";N;s:8:\"priority\";i:1;s:9:\"data_json\";a:0:{}s:13:\"dismissal_key\";N;s:12:\"capabilities\";s:20:\"wpseo_manage_options\";s:16:\"capability_check\";s:3:\"all\";s:14:\"yoast_branding\";b:0;}}}');
INSERT INTO `wp_usermeta` VALUES('52', '2', 'wp_user-settings', 'editor=tinymce');
INSERT INTO `wp_usermeta` VALUES('53', '2', 'wp_user-settings-time', '1569498087');
INSERT INTO `wp_usermeta` VALUES('54', '2', 'closedpostboxes_page', 'a:1:{i:0;s:10:\"wpseo_meta\";}');
INSERT INTO `wp_usermeta` VALUES('55', '2', 'metaboxhidden_page', 'a:5:{i:0;s:12:\"revisionsdiv\";i:1;s:16:\"commentstatusdiv\";i:2;s:11:\"commentsdiv\";i:3;s:7:\"slugdiv\";i:4;s:9:\"authordiv\";}');
INSERT INTO `wp_usermeta` VALUES('56', '3', 'nickname', 'sbyr-rcib-admin');
INSERT INTO `wp_usermeta` VALUES('57', '3', 'first_name', 'Simon');
INSERT INTO `wp_usermeta` VALUES('58', '3', 'last_name', 'Byrne');
INSERT INTO `wp_usermeta` VALUES('59', '3', 'description', '');
INSERT INTO `wp_usermeta` VALUES('60', '3', 'rich_editing', 'true');
INSERT INTO `wp_usermeta` VALUES('61', '3', 'syntax_highlighting', 'true');
INSERT INTO `wp_usermeta` VALUES('62', '3', 'comment_shortcuts', 'false');
INSERT INTO `wp_usermeta` VALUES('63', '3', 'admin_color', 'fresh');
INSERT INTO `wp_usermeta` VALUES('64', '3', 'use_ssl', '0');
INSERT INTO `wp_usermeta` VALUES('65', '3', 'show_admin_bar_front', 'true');
INSERT INTO `wp_usermeta` VALUES('66', '3', 'locale', '');
INSERT INTO `wp_usermeta` VALUES('67', '3', 'wp_capabilities', 'a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `wp_usermeta` VALUES('68', '3', 'wp_user_level', '10');
INSERT INTO `wp_usermeta` VALUES('69', '3', 'dismissed_wp_pointers', '');
INSERT INTO `wp_usermeta` VALUES('70', '3', '_yoast_wpseo_profile_updated', '1569499016');
INSERT INTO `wp_usermeta` VALUES('71', '3', 'session_tokens', 'a:1:{s:64:\"31bd7f6ed254284bfb84422d70234f0d1e07a318f9d96dcaa60ffc1c21920f31\";a:4:{s:10:\"expiration\";i:1569671882;s:2:\"ip\";s:14:\"217.217.154.40\";s:2:\"ua\";s:78:\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0\";s:5:\"login\";i:1569499082;}}');
INSERT INTO `wp_usermeta` VALUES('72', '3', 'wp_dashboard_quick_press_last_post_id', '605');
INSERT INTO `wp_usermeta` VALUES('73', '3', 'wp_yoast_notifications', 'a:1:{i:0;a:2:{s:7:\"message\";s:232:\"<strong>Huge SEO Issue: You\'re blocking access to robots.</strong> You must <a href=\"http://localhost:8888/eurorescue-wp/wp-admin/options-reading.php\">go to your Reading Settings</a> and uncheck the box for Search Engine Visibility.\";s:7:\"options\";a:9:{s:4:\"type\";s:5:\"error\";s:2:\"id\";s:32:\"wpseo-dismiss-blog-public-notice\";s:5:\"nonce\";N;s:8:\"priority\";i:1;s:9:\"data_json\";a:0:{}s:13:\"dismissal_key\";N;s:12:\"capabilities\";s:20:\"wpseo_manage_options\";s:16:\"capability_check\";s:3:\"all\";s:14:\"yoast_branding\";b:0;}}}');
INSERT INTO `wp_usermeta` VALUES('74', '2', 'closedpostboxes_attributes', 'a:2:{i:0;s:12:\"postimagediv\";i:1;s:10:\"wpseo_meta\";}');
INSERT INTO `wp_usermeta` VALUES('75', '2', 'metaboxhidden_attributes', 'a:1:{i:0;s:7:\"slugdiv\";}');
INSERT INTO `wp_usermeta` VALUES('76', '2', 'closedpostboxes_cover', 'a:3:{i:0;s:16:\"tagsdiv-post_tag\";i:1;s:12:\"postimagediv\";i:2;s:10:\"wpseo_meta\";}');
INSERT INTO `wp_usermeta` VALUES('77', '2', 'metaboxhidden_cover', 'a:1:{i:0;s:7:\"slugdiv\";}');
/*!40000 ALTER TABLE `wp_usermeta` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
