CREATE TABLE `wp_yoast_seo_meta` (  `object_id` bigint(20) unsigned NOT NULL,  `internal_link_count` int(10) unsigned DEFAULT NULL,  `incoming_link_count` int(10) unsigned DEFAULT NULL,  UNIQUE KEY `object_id` (`object_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_yoast_seo_meta` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_yoast_seo_meta` VALUES('3', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('23', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('70', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('109', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('235', '1', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('249', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('261', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('263', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('312', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('333', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('334', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('335', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('352', '0', '1');
INSERT INTO `wp_yoast_seo_meta` VALUES('465', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('466', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('467', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('533', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('538', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('539', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('541', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('542', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('543', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('544', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('545', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('546', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('547', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('550', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('551', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('552', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('553', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('554', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('562', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('563', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('566', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('585', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('587', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('594', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('609', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('608', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('583', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('605', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('607', '0', '0');
INSERT INTO `wp_yoast_seo_meta` VALUES('560', '0', '0');
/*!40000 ALTER TABLE `wp_yoast_seo_meta` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
