CREATE TABLE `wp_yoast_seo_links` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `url` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,  `post_id` bigint(20) unsigned NOT NULL,  `target_post_id` bigint(20) unsigned NOT NULL,  `type` varchar(8) COLLATE utf8mb4_unicode_520_ci NOT NULL,  PRIMARY KEY (`id`),  KEY `link_direction` (`post_id`,`type`)) ENGINE=MyISAM AUTO_INCREMENT=103 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40000 ALTER TABLE `wp_yoast_seo_links` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_yoast_seo_links` VALUES('5', 'http://www.autoaidbreakdown.co.uk', '70', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('6', 'http://www.autonational.co.uk', '70', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('66', 'mailto:contact@eurorescue.co.uk', '352', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('67', 'mailto:quality@eurorescue.co.uk', '352', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('78', 'http://www.allaboutcookies.org/', '263', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('79', 'http://tools.google.com/dlpage/gaoptout', '263', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('80', 'http://www.allaboutcookies.org/', '263', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('81', 'mailto:DPM@rcib.co.uk', '3', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('91', 'mailto:dpm@rcib.co.uk', '261', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('92', 'mailto:complaint.info@financial-ombudsman.org.uk', '261', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('93', 'http://www.financial-ombudsman.org.uk', '261', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('94', 'http://localhost:8888/eurorescue-wp/contact/', '235', '352', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('95', 'https://eurorescue.co.uk/documents/EuroRescue%20Policy%20Document.pdf', '235', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('96', 'https://eurorescue.co.uk/documents/Euro%20Rescue%20Notice.pdf', '235', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('97', 'https://eurorescue.co.uk/documents/Privacy%20Notice.pdf', '235', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('98', 'https://eurorescue.co.uk/documents/EuroBreak%20Product%20Information%20Document.pdf', '235', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('99', 'https://eurorescue.co.uk/documents/EuroRescue%20(Limited%20Europe)%20Product%20Information%20Document.pdf', '235', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('100', 'https://eurorescue.co.uk/documents/EuroRescue%20(Europe)%20Product%20Information%20Document.pdf', '235', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('101', 'https://eurorescue.co.uk/documents/EuroRescue%20Plus%20(Limited%20Europe)%20Product%20Information%20Document.pdf', '235', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('102', 'https://eurorescue.co.uk/documents/EuroRescue%20Plus%20(Europe)%20Product%20Information%20Document.pdf', '235', '0', 'external');
/*!40000 ALTER TABLE `wp_yoast_seo_links` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
